SistemaConsorcio/Models/Propietario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaConsorcio.Models
{
    public class Propietario
    {
        public int PropietarioId { get; set; }
        [Required(ErrorMessage ="Debe ingresar un apellido y nombre")]
        [Display(Name = "Apellido y Nombre")]
        public string PropietarioNombre { get; set; }
        [Required(ErrorMessage = "El propietario debe tener un cuil")]
        [Display(Name = "CUIL (Ingrese el numero sin guiones)")]
        [Range(9999999999,99999999999,ErrorMessage = "Ingrese un cuil valido")]
        public long PropietarioCuil { get; set; }
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Ingrese un mail valido")] 
        public string PropietarioEmail { get; set; }
        [Display(Name = "Enviar mails?")]
        public bool PropietarioSuscripto { get; set; }
        [Display (Name = "Dirección")]
        [Required(ErrorMessage = "La direccion es obligatoria")]
        public string PropietarioDireccion { get; set; }
        [Display (Name = "Telefono")]
        public Int64? PropietarioTelefono { get; set; }
    }
}

SistemaConsorcio/Controllers/PropietariosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class PropietariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PropietariosController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> getPropietarios()
        {
            var propietarios = _context.Propietario;
            return PartialView("_Index",await propietarios.OrderBy(p => p.PropietarioNombre).ToListAsync());
        }

        public async Task<ViewAsPdf> ReportePropietarios()//si voy a generar byte le pongo async
        {
            GeneralesController mail = new GeneralesController(_context);//controlador del mail
            var pdf = new ViewAsPdf("_ReportePropietarios",_context.Propietario.ToList())
            {
                PageSize = Size.A4
            };
            byte[] bytes = await pdf.BuildFile(this.ControllerContext);//genera pdf para enviar, se podria guardar en una variable
            mail.enviarMailAdjunto(bytes,"luchosan74@gmail.com","prueba","eh guacho","InformePropietarios");//ejemplo llamada para mandar mail
            return pdf;
        }
        // GET: Propietarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propietario = await _context.Propietario
               .FirstOrDefaultAsync(m => m.PropietarioId == id);
            if (propietario == null)
            {
                return NotFound();
            }

            return View(propietario);
        }

        // GET: Propietarios/Create
        public IActionResult Create()
        {
            ViewData["DepartamentoId"] = new SelectList(_context.TipoDepartamento, "TipoDepartamentoId", "TipoDepartamentoLetra");
            return PartialView("_Create");
        }

        [HttpPost]
        public IActionResult Agregar([Bind("PropietarioNombre,PropietarioCuil,PropietarioEmail,PropietarioSuscripto,PropietarioDireccion,PropietarioTelefono")] Propietario propietario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(propietario);
                _context.SaveChanges();
                return Json(new { exitoso = true, alerta = "Agregado correctamente" });
            }
            return Json(new { exitoso = false, alerta = "Error al agregar Departamento" });
        }

        // GET: Propietarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propietario = await _context.Propietario.FindAsync(id);
            if (propietario == null)
            {
                return NotFound();
            }
            return PartialView("_Edit",propietario);
        }

        [HttpPost]
        public async Task<IActionResult> ActualizarPropietario([Bind("PropietarioId,PropietarioNombre,PropietarioCuil,PropietarioEmail,PropietarioSuscripto,PropietarioDireccion,PropietarioTelefono")] Propietario propietario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(propietario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropietarioExists(propietario.PropietarioId))
                    {
                        return Json(new { exitoso = false, alerta = "Error en la actualizacion" });
                    }
                    else
                    {
                        throw;
                    }
                }
                return Json(new { exitoso = true, alerta = "Actualizado correctamente" });
            }
            return View(propietario);
        }

        // GET: Propietarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var cantDepartamentos = _context.Departamento.Where(d => d.PropietarioId == id).Count();
            if (cantDepartamentos == 0)
            {
                var propietario = await _context.Propietario.FindAsync(id);
                _context.Propietario.Remove(propietario);
                await _context.SaveChangesAsync();
                return Json(new { eliminado = true, msg = "Propietario eliminado" });
            }
            else
            {
                return Json(new { eliminado = false, msg = "No se puede eliminar. Tiene departamentos asociados" });
            }
        }

        private bool PropietarioExists(int id)
        {
            return _context.Propietario.Any(e => e.PropietarioId == id);
        }
    }
}

SistemaConsorcio/Views/Propietarios/_Create.cshtml
@model SistemaConsorcio.Models.Propietario

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Nuevo Propietario</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form asp-action="Create" class="submit-create">
            <div class="modal-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioNombre" class="control-label"></label>
                        <input asp-for="PropietarioNombre" class="form-control PropietarioNombre" />
                        <span asp-validation-for="PropietarioNombre" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioCuil" class="control-label"></label>
                        <input asp-for="PropietarioCuil" class="form-control PropietarioCuil" />
                        <span asp-validation-for="PropietarioCuil" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioDireccion" class="control-label"></label>
                        <input asp-for="PropietarioDireccion" class="form-control PropietarioDireccion" />
                        <span asp-validation-for="PropietarioDireccion" class="text-danger"></span>
                    </div>
                    <div class="col form-group">
                        <label asp-for="PropietarioTelefono" class="control-label"></label>
                        <input asp-for="PropietarioTelefono" class="form-control PropietarioTelefono" />
                        <span asp-validation-for="PropietarioTelefono" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioEmail" class="control-label"></label>
                        <input asp-for="PropietarioEmail" class="form-control PropietarioEmail" />
                        <span asp-validation-for="PropietarioEmail" class="text-danger"></span>
                    </div>
                    <div class="switch_box box_1 form-group col">
                        <label class="form-check-label">
                            <p class="control-label">@Html.DisplayNameFor(model => model.PropietarioSuscripto)</p><input type="checkbox" class="switch_1 PropietarioSuscripto" asp-for="PropietarioSuscripto" style="margin-bottom:20px;">
                        </label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark btn-quitarmodal" data-dismiss="modal">Cancelar</button>
                <input type="submit" value="Agregar" class="btn btn-primary btn-agregar" />
            </div>
        </form>
    </div>


@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    $('.submit-create').on('submit', function (e) {
        e.preventDefault();
        $('.btn-agregar').attr("disabled",false);
        let PropietarioSuscripto = false;
        if ($('.PropietarioSuscripto').prop('checked')) {
            PropietarioSuscripto = true;
        }
        var prop = {
            "PropietarioNombre": $('.PropietarioNombre').val(),
            "PropietarioCuil": $('.PropietarioCuil').val(),
            "PropietarioEmail": $('.PropietarioEmail').val(),
            "PropietarioSuscripto": PropietarioSuscripto,
            "PropietarioDireccion": $('.PropietarioDireccion').val(),
            "PropietarioTelefono": $('.PropietarioTelefono').val()
        }
        if ($(this).valid()) {
            $.ajax({
                url: "@Url.Action("Agregar","Propietarios")",
                method: 'Post',
                data: {
                    propietario: prop
                }
            }).done((msg) => {
                if (msg.exitoso == true) {
                    alertify.success(msg.alerta);
                    $('.contenedor').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
                    $('.contenedor').load("@Url.Action("getPropietarios","Propietarios")");
                    $('#ModalCU').modal('hide');
                    $('.btn-agregar').attr("disabled",true);
                } else {
                    alertify.warning(msg.alerta);
                    $('.btn-agregar').attr("disabled",false);
                }
            }).fail((err) => {
                alertify.error("Algo fallo al actualizar");
                $('.btn-agregar').attr("disabled",false);
            });
        }
    });
</script>

SistemaConsorcio/Views/Propietarios/_Edit.cshtml
@model SistemaConsorcio.Models.Propietario

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">@Html.DisplayFor(model => model.PropietarioNombre) - @Html.DisplayFor(model => model.PropietarioCuil)</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form asp-action="Edit" class="submit-edit" data-id="@Model.PropietarioId">
            <div class="modal-body">
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioNombre" class="control-label"></label>
                        <input asp-for="PropietarioNombre" class="form-control PropietarioNombre" />
                        <span asp-validation-for="PropietarioNombre" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioCuil" class="control-label"></label>
                        <input asp-for="PropietarioCuil" class="form-control PropietarioCuil" />
                        <span asp-validation-for="PropietarioCuil" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioDireccion" class="control-label"></label>
                        <input asp-for="PropietarioDireccion" class="form-control PropietarioDireccion" />
                        <span asp-validation-for="PropietarioDireccion" class="text-danger"></span>
                    </div>
                    <div class="col form-group">
                        <label asp-for="PropietarioTelefono" class="control-label"></label>
                        <input asp-for="PropietarioTelefono" class="form-control PropietarioTelefono" />
                        <span asp-validation-for="PropietarioTelefono" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label asp-for="PropietarioEmail" class="control-label"></label>
                        <input asp-for="PropietarioEmail" class="form-control PropietarioEmail" />
                        <span asp-validation-for="PropietarioEmail" class="text-danger"></span>
                    </div>
                    <div class="switch_box box_1 form-group col">
                        <label class="form-check-label">
                            <p class="control-label">@Html.DisplayNameFor(model => model.PropietarioSuscripto)</p><input type="checkbox" class="switch_1 PropietarioSuscripto" asp-for="PropietarioSuscripto" style="margin-bottom:20px;">
                        </label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark btn-quitarmodal" data-dismiss="modal">Cancelar</button>
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </form>
    </div>

@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    $('.submit-edit').on('submit', function (e) {
        e.preventDefault();
        let PropietarioSuscripto = false;
        if ($('.PropietarioSuscripto').prop('checked')) {
            PropietarioSuscripto = true;
        }
        var prop = {
            "PropietarioId": $(this).data('id'),
            "PropietarioNombre": $('.PropietarioNombre').val(),
            "PropietarioCuil": $('.PropietarioCuil').val(),
            "PropietarioEmail": $('.PropietarioEmail').val(),
            "PropietarioSuscripto": PropietarioSuscripto,
            "PropietarioDireccion": $('.PropietarioDireccion').val(),
            "PropietarioTelefono": $('.PropietarioTelefono').val()
        }
        if ($(this).valid()) {
            $.ajax({
                url: "@Url.Action("ActualizarPropietario","Propietarios")",
                method: 'Post',
                data: {
                    propietario: prop
                }
            }).done((msg) => {
                if (msg.exitoso == true) {
                    alertify.success(msg.alerta);
                    $('.contenedor').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
                    $('.contenedor').load("@Url.Action("getPropietarios","Propietarios")");
                    $('#ModalCU').modal('hide');
                } else {
                    alertify.warning(msg.alerta);
                }
            }).fail((err) => {
                alertify.error("Algo fallo al actualizar");
            });
        }
    });
</script>

SistemaConsorcio/Views/Propietarios/_Index.cshtml
@model IEnumerable<SistemaConsorcio.Models.Propietario>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">
                        Listado de propietarios <span style="display: block;float: right;"><a href="" class="btn-modal" data-toggle="modal" data-target="#ModalCU" data-action="@Url.Action("Create","Propietarios")"><i class="fas fa-plus-circle fa-2x"></i></a></span>
                    </h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class=" text-primary">
                            <th>
                                Propietario
                            </th>
                            <th>
                                CUIL
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PropietarioEmail)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PropietarioDireccion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PropietarioTelefono)
                            </th>
                            <th>
                                Suscripto?
                            </th>
                            <th></th>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PropietarioNombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PropietarioCuil)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PropietarioEmail)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PropietarioDireccion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PropietarioTelefono)
                                    </td>
                                    <td>
                                        @if (item.PropietarioSuscripto == false)
                                        {
                                            <span>NO</span>
                                        }
                                        else
                                        {
                                            <span>SI</span>
                                        }
                                    </td>
                                    <td>
                                        <a asp-action="Edit" data-action="@Url.Action("Edit","Propietarios")/@item.PropietarioId" class="btn btn-success btn-modal" data-toggle="modal" data-target="#ModalCU"><i class="fas fa-pencil-alt"></i></a>
                                        <a asp-action="Delete" data-action="@Url.Action("Delete")" data-id="@item.PropietarioId" class="btn btn-danger btn-delete-ajax"><i class="far fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SistemaConsorcio/Views/Propietarios/_ReportePropietarios.cshtml
@model IEnumerable<SistemaConsorcio.Models.Propietario>

<h1>Reporte Propietarios</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Cuil</th>
            <th scope="col">Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.PropietarioNombre)</td>
                <td>@Html.DisplayFor(modelItem => item.PropietarioCuil)</td>
                <td>@Html.DisplayFor(modelItem => item.PropietarioEmail)</td>
            </tr>
        }
    </tbody>
</table>