SistemaConsorcio/Controllers/DepartamentosController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class DepartamentosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartamentosController(ApplicationDbContext context)
        {
            _context = context;
        }
        //Trae los departamentos
        public async Task<IActionResult> getDepartamentos() {         
            var departamentos = _context.Departamento.Include(d => d.DepartamentoPropietario).Include(d => d.DepartamentoTipo);
            foreach (Departamento departamento in departamentos)
            {
                departamento.DepartamentoSaldo = await calcularSaldo(departamento.DepartamentoId, DateTime.Now);
            }
            return PartialView("_ListaDepartamentos", await departamentos.ToListAsync());
        }
        //Trae un departamento para editar
        public async Task<IActionResult> getDepartamento(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var departamento = await _context.Departamento.FindAsync(id);
            if (departamento == null)
            {
                return NotFound();
            }
            ViewData["PropietarioId"] = new SelectList(_context.Propietario, "PropietarioId", "PropietarioNombre", departamento.PropietarioId);
            ViewData["TipoDepartamentoId"] = new SelectList(_context.TipoDepartamento, "TipoDepartamentoId", "TipoDepartamentoLetra", departamento.TipoDepartamentoId);
            return PartialView("_Edit", departamento);
        }
        //Envia la ultima expensa del departamento
        public async Task<IActionResult> enviarUltimaExpensa(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var departamento = await _context.Departamento.Include(d => d.DepartamentoPropietario).Where(d => d.DepartamentoId == id).FirstAsync();
            var ultimaExpensa = await _context.Expensa.OrderByDescending(e => e.ExpensaPeriodo).FirstAsync();
            byte[] bytes = ultimaExpensa.ExpensaPdf;
            GeneralesController mail = new GeneralesController(_context);//controlador del mail
            mail.enviarMailAdjunto(bytes,
                                    departamento.DepartamentoPropietario.PropietarioEmail,
                                    "Expensa " + ultimaExpensa.ExpensaPeriodo.ToString(string.Format("dd/MM/yyyy")),
                                    "Se adjunta el resumen de la expensa perteneciente al periodo: " + ultimaExpensa.ExpensaPeriodo.ToString(string.Format("dd/MM/yyyy")),
                                    "Resumen Expensa " + ultimaExpensa.ExpensaPeriodo.ToString(string.Format("dd/MM/yyyy")));//ejemplo llamada para mandar mail
            return Json(true);
        }
        //Calcula el saldo total que debe el departamento
        public async Task<decimal> calcularSaldo(int idDepartamento, DateTime fecha)
        {
            var general = await _context.General.FirstOrDefaultAsync();
            var pagosPendientes = await _context.PagoPendiente.Where(p => p.DepartamentoId == idDepartamento).Include(p => p.PagoPendienteExpensa).ToListAsync();
            decimal saldo = 0;
            foreach (PagoPendiente pendiente in pagosPendientes)
            {
                var periodoPago = pendiente.PagoPendienteExpensa.ExpensaPeriodo;
                if (fecha < pendiente.PagoPendienteFechaPrimerVencimiento)//considero q el primer vencimiento es el 5, no vencio
                {
                    saldo += pendiente.PagoPendienteImporte;
                }
                else if (fecha < pendiente.PagoPendienteFechaSegundoVencimiento)//considero q el segundo vencimiento es el 10, aplico primer vencimiento
                {
                    saldo += pendiente.PagoPendientePrimerVencimiento;
                }
                else if (fecha < pendiente.PagoPendienteFechaTercerVencimiento)//considero que el tercer vencimiento es el 10, aplico segundo vencimiento
                {
                    saldo += pendiente.PagoPendienteSegundoVencimiento;
                }
                else //aplico tercer vencimiento
                {
                    saldo += pendiente.PagoPendienteTercerVencimiento;
                }
            }
            return saldo;
        }
        public async Task<IActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var departamento = await _context.Departamento.Include(d => d.DepartamentoTipo).Include(d => d.DepartamentoPropietario).Where(d => d.DepartamentoId == id).FirstAsync();
            if (departamento == null)
            {
                return NotFound();
            }
            ViewBag.saldo = await calcularSaldo(departamento.DepartamentoId,DateTime.Now);
            ViewBag.pendientes = await _context.PagoPendiente.Include(p => p.PagoPendienteExpensa).Where(p => p.DepartamentoId == departamento.DepartamentoId).ToListAsync();
            DateTime actual = DateTime.Now;
            foreach (PagoPendiente pendiente in ViewBag.pendientes)
            {
                if (actual < pendiente.PagoPendienteFechaPrimerVencimiento)
                {
                    pendiente.PagoPendienteImporte = pendiente.PagoPendienteImporte;
                }
                else if (actual < pendiente.PagoPendienteFechaSegundoVencimiento)
                {
                    pendiente.PagoPendienteImporte = pendiente.PagoPendientePrimerVencimiento;
                }
                else if (actual < pendiente.PagoPendienteFechaTercerVencimiento)
                {
                    pendiente.PagoPendienteImporte = pendiente.PagoPendienteSegundoVencimiento;
                }
                else
                {
                    pendiente.PagoPendienteImporte = pendiente.PagoPendienteTercerVencimiento;
                }
            }
            return PartialView("Detalles",departamento);
        }

        // GET: Departamentos/Create
        public IActionResult Create()
        {
            var tipoDeptos =
            _context.TipoDepartamento.Select(t => new
            {
                t.TipoDepartamentoId,
                t.TipoDepartamentoLetra,
                TipoCoeficiente = string.Format("{0} (% {1})", t.TipoDepartamentoLetra, t.TipoDepartamentoCoeficiente)
            })
            .Where(t => !t.TipoDepartamentoLetra.Contains('Z'))
                        .ToList();
            ViewData["PropietarioId"] = new SelectList(_context.Propietario, "PropietarioId", "PropietarioNombre");
            ViewData["TipoDepartamentoId"] = new SelectList(tipoDeptos, "TipoDepartamentoId", "TipoCoeficiente");
            return PartialView("_Create");
        }

        // POST: Departamentos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public IActionResult Agregar([Bind("TipoDepartamentoId,DepartamentoPiso,PropietarioId,DepartamentoCochera,DepartamentoCantidadCochera,DepartamentoSufix")] Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                if (!DepartamentoRepeat(departamento))
                {
                    if (ValidCoeficiente(departamento))
                    {
                        _context.Add(departamento);
                        _context.SaveChanges();
                        return Json(new { exitoso = true, alerta = "Agregado correctamente" });
                    }
                    else
                    {
                        return Json(new { exitoso = false, alerta = "El departamento excede el 100%" });
                    }
                }
                else
                {
                    return Json(new { exitoso = false, alerta = "Departamento repetido" });
                }
            }
            else
            {
                return Json(new { exitoso = false, alerta = "Error al agregar Departamento" });
            }
        }

        [HttpPost]
        public ActionResult ActualizarDepartamento(Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Departamento updateDepartamento = _context.Departamento.Find(departamento.DepartamentoId);
                    updateDepartamento.DepartamentoPiso = departamento.DepartamentoPiso; 
                    updateDepartamento.DepartamentoCochera = departamento.DepartamentoCochera; 
                    updateDepartamento.PropietarioId = departamento.PropietarioId; 
                    updateDepartamento.TipoDepartamentoId = departamento.TipoDepartamentoId;
                    updateDepartamento.DepartamentoCantidadCochera = departamento.DepartamentoCantidadCochera;
                    updateDepartamento.DepartamentoSufix = departamento.DepartamentoSufix;
                    if (!DepartamentoRepeat(updateDepartamento))
                    {
                        _context.SaveChanges();
                        return Json(new { exitoso = true, alerta = "Actualizado correctamente" });
                    }
                    else
                    {
                        return Json(new { exitoso = false, alerta = "Departamento repetido" });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartamentoExists(departamento.DepartamentoId))
                    {

SistemaConsorcio/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class PagosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PagosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pagos
        public IActionResult Index()
        {
            return PartialView();
        }

        public async Task<IActionResult> getPagos(DateTime? fechaDesde,DateTime? fechaHasta)
        {
            var pagos = from p in _context.Pago
                           select p;
            pagos = _context.Pago.Include(p => p.PagoDepartamento).Include(p => p.PagoDepartamento.DepartamentoTipo).OrderByDescending(p => p.PagoFecha);
            DateTime date = DateTime.Now;
            DateTime oPrimerDiaDelMes = new DateTime(date.Year, date.Month, 1);
            if (!String.IsNullOrEmpty(fechaDesde.ToString()))
            {
                pagos = pagos.Where(p => p.PagoFecha >= fechaDesde);
            }
            else
            {
                pagos = pagos.Where(p => p.PagoFecha >= oPrimerDiaDelMes);
            }
            if (!String.IsNullOrEmpty(fechaHasta.ToString()))
            {
                pagos = pagos.Where(p => p.PagoFecha <= fechaHasta);
            }
            else
            {
                DateTime oUltimoDiaDelMes = oPrimerDiaDelMes.AddMonths(1).AddDays(-1);
                pagos = pagos.Where(p => p.PagoFecha <= oUltimoDiaDelMes);
            }
            ViewBag.totalBanco = pagos.Where(p => p.PagoForma == "Cuenta bancaria").Sum(p => p.PagoImporte);
            ViewBag.totalCaja = pagos.Where(p => p.PagoForma == "Contado").Sum(p => p.PagoImporte);
            ViewBag.total = ViewBag.totalBanco + ViewBag.totalCaja;
            return PartialView("_Listado",await pagos.ToListAsync());
        }
        // GET: Pagos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago
                .Include(p => p.PagoDepartamento)
                .FirstOrDefaultAsync(m => m.PagoId == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // GET: Pagos/Create
        public IActionResult Create()
        {
            var departamentos =
                      _context.Departamento.Include(d => d.DepartamentoTipo)
                        .Select(d => new
                        {
                            d.DepartamentoId,
                            NombreDeparamento = string.Format("{0}°{1}", d.DepartamentoPiso, d.DepartamentoTipo.TipoDepartamentoLetra)
                        })
                        .ToList();
            ViewData["DepartamentoId"] = new SelectList(departamentos, "DepartamentoId", "NombreDeparamento");
            ViewData["ExpensaId"] = new SelectList(_context.Expensa, "ExpensaId", "ExpensaId");
            return PartialView();
        }

        // POST: Pagos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("PagoId,PagoFecha,DepartamentoId,PagoImporte,PagoForma")] Pago pago, int TipoPago)
        {
            if (ModelState.IsValid)
            {
                if (TipoPago == 0)
                {
                    await eliminarPagosPendientesDepartamento(pago.DepartamentoId);
                }
                _context.Add(pago);
                await _context.SaveChangesAsync();
                return Json(new { exitoso = true, alerta = "Pago cargado" });
            }
            return Json(new { exitoso = false, alerta = "Error al cargar pago" });
        }

        public async Task<IActionResult> eliminarPagosPendientesDepartamento(int idDepartamento)
        {
            var pendientes = await _context.PagoPendiente.Where(pp => pp.DepartamentoId == idDepartamento).ToListAsync();
            var controladorPendientes = new PagoPendientesController(_context);
            foreach (PagoPendiente pendiente in pendientes)
            {
                await controladorPendientes.Delete(pendiente.PagoPendienteId);   
            }
            return Json(true);
        }
        // GET: Pagos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago.FindAsync(id);
            if (pago == null)
            {
                return NotFound();
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamento, "DepartamentoId", "DepartamentoId", pago.DepartamentoId);
            return View(pago);
        }

        // POST: Pagos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PagoId,PagoFecha,DepartamentoId,PagoImporte,PagoForma")] Pago pago)
        {
            if (id != pago.PagoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagoExists(pago.PagoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamento, "DepartamentoId", "DepartamentoId", pago.DepartamentoId);
            return View(pago);
        }

        // GET: Pagos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago
                .Include(p => p.PagoDepartamento)
                .FirstOrDefaultAsync(m => m.PagoId == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // POST: Pagos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pago = await _context.Pago.FindAsync(id);
            _context.Pago.Remove(pago);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagoExists(int id)
        {
            return _context.Pago.Any(e => e.PagoId == id);
        }
    }
}

SistemaConsorcio/Views/Pagos/Create.cshtml
@model SistemaConsorcio.Models.Pago

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Nuevo Pago</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form asp-action="Create" class="submit-create">
        <div class="modal-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col form-group">
                    <label asp-for="DepartamentoId" class="control-label"></label>
                    <select asp-for="DepartamentoId" class="form-control DepartamentoId" asp-items="ViewBag.DepartamentoId">
                        <option selected disabled>Elija un departamento...</option>
                    </select>
                    <span asp-validation-for="DepartamentoId" class="text-danger"></span>
                </div>
                <div class="col form-group">
                    <label asp-for="PagoFecha" class="control-label"></label>
                    <input asp-for="PagoFecha" class="form-control PagoFecha" required/>
                    <span asp-validation-for="PagoFecha" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col form-group">
                    <label asp-for="PagoImporte" class="control-label">Tipo de pago</label>
                    <select class="form-control TipoPago">
                        <option value="0">Importe Total</option>
                        <option value="1">Importe Parcial</option>
                    </select>
                </div>
                <div class="col form-group">
                    <label asp-for="PagoImporte" class="control-label">Importe ($)</label>
                    <input asp-for="PagoImporte" class="form-control PagoImporte" disabled value="0" />
                    <span asp-validation-for="PagoImporte" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col form-group">
                    <label asp-for="PagoForma" class="control-label"></label>
                    <select asp-for="PagoForma" class="form-control PagoForma">
                        <option value="Cuenta bancaria">Cuenta bancaria</option>
                        <option value="Contado">Contado</option>
                    </select>
                    <span asp-validation-for="PagoForma" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-dark btn-quitarmodal" data-dismiss="modal">Cancelar</button>
            <input type="submit" value="Agregar" class="btn btn-primary btn-agregar" />
        </div>
    </form>
</div>


@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    $('.DepartamentoId').on('change', function () {
               $(".saldo").html('0');
               $(".PagoImporte").val(0);
               $.ajax({
                   url: "@Url.Action("calcularSaldo","Departamentos")",
                   type: 'Get',
                   data: {
                       idDepartamento: $('.DepartamentoId').val(),
                       fecha:$('.PagoFecha').val()
                   },
                   success: (data) => {
                       $(".saldo").html(data);
                       $(".PagoImporte").val(data);
                    },
                    error: function (err) {
                        alertify.error("Error: " + err.msg);
                    }
                });
    });
        $('.PagoFecha').on('change', function () {
               $(".saldo").html('0');
               $(".PagoImporte").val(0);
               $.ajax({
                   url: "@Url.Action("calcularSaldo","Departamentos")",
                   type: 'Get',
                   data: {
                       idDepartamento: $('.DepartamentoId').val(),
                       fecha:$(this).val()
                   },
                   success: (data) => {
                       $(".saldo").html(data);
                       $(".PagoImporte").val(data);
                    },
                    error: function (err) {
                        alertify.error("Error: " + err.msg);
                    }
                });
    });
    $('.TipoPago').on('change', function () {
        if ($(this).val() == 0) {
            $('.PagoImporte').prop('disabled',true);
        } else if ($(this).val() == 1) {
            $('.PagoImporte').prop('disabled', false);
        };
    });
    $('.submit-create').on('submit', function (e) {
        e.preventDefault();
        $('.btn-agregar').attr("disabled",true);
        var payment = {
            "DepartamentoId": $('.DepartamentoId').val(),
            "PagoFecha": $('.PagoFecha').val(),
            "PagoImporte": $('.PagoImporte').val(),
            "PagoForma": $('.PagoForma').val()
        }
        if ($(this).valid()) {
            alertify.confirm('Confirmar pago', 'Esta seguro que quiere cargar este pago?', () => {
                $.ajax({
                    url: "@Url.Action("Create","Pagos")",
                    method: 'Post',
                    data: {
                        pago: payment,
                        "TipoPago": $('.TipoPago').val()
                    }
                }).done((msg) => {
                    if (msg.exitoso == true) {
                        alertify.success(msg.alerta);
                        $('.contenido-tabla').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
                        $('.contenido-tabla').load("@Url.Action("getPagos","Pagos")");
                        $('#ModalCU').modal('hide');
                        $('.btn-agregar').attr("disabled",false);
                    } else {
                        alertify.warning(msg.alerta);
                        $('.btn-agregar').attr("disabled",false);
                    }
                }).fail((err) => {
                    alertify.error("Algo fallo al actualizar");
                    $('.btn-agregar').attr("disabled",false);
                });
            }, function () { alertify.error('Pago cancelado') });
        }
    });
</script>

SistemaConsorcio/Views/Pagos/Index.cshtml
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">
                        Listado de pagos
                        <span style="display: block;float: right;">
                            <a href="" class="" data-toggle="modal" data-target="#FilterModal">
                                <i class="fas fa-search fa-2x"></i>
                            </a>
                            <!--    <a href="" class="btn-modal" data-toggle="modal" data-target="#ModalCU" data-action="@Url.Action("create","Pagos")">
            <i class="fas fa-plus-circle fa-2x"></i>
        </a>-->
                        </span>
                    </h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive contenido-tabla">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="FilterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Filtrar pagos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col form-group">
                        <label class="control-label">Desde</label>
                        <input type="date" class="form-control FechaDesde" />
                    </div>
                    <div class="col form-group">
                        <label class="control-label">Hasta</label>
                        <input type="date" class="form-control FechaHasta" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary btn-filtrar">Filtrar</button>
            </div>
        </div>
    </div>
</div>
<script>
    $('.contenido-tabla').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
    $('.contenido-tabla').load("@Url.Action("getPagos","Pagos")");
    $('.btn-filtrar').on('click', function () {
            $('.contenido-tabla').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
               $.ajax({
                   url: "@Url.Action("getPagos","Pagos")",
                   type: 'Get',
                   data: {
                       fechaDesde: $('.FechaDesde').val(),
                       fechaHasta: $('.FechaHasta').val()
                   },
                   success: (data) => {
                       $(".contenido-tabla").html(data);
                       $('#FilterModal').modal('hide');
                    },
                    error: function (err) {
                        alertify.error("Error: " + err.msg);
                    }
                });
    });
</script>

SistemaConsorcio/Views/Pagos/_Listado.cshtml
@model IEnumerable<SistemaConsorcio.Models.Pago>
<table class="table table-hover">
    <thead class=" text-primary">
    <th>
        @Html.DisplayNameFor(model => model.PagoDepartamento)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.PagoFecha)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.PagoImporte)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.PagoForma)
    </th>
    <th></th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @if (item.PagoDepartamento.DepartamentoPiso == 0)
            {
                <td>
                    PB @Html.DisplayFor(modelItem => item.PagoDepartamento.DepartamentoTipo.TipoDepartamentoLetra)
                </td>
            }
            else
            {
            <td>
                @Html.DisplayFor(modelItem => item.PagoDepartamento.DepartamentoPiso)°@Html.DisplayFor(modelItem => item.PagoDepartamento.DepartamentoTipo.TipoDepartamentoLetra)
            </td>            }
            <td>
                @item.PagoFecha.ToString(string.Format("dd/MM/yyyy"))
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.PagoImporte)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PagoForma)
            </td>
        </tr>
        }
    </tbody>
</table>
<table class="table table-hover">
    <thead class=" text-primary">
        <th>
            Total por banco
        </th>
        <th>
            Total contado
        </th>
        <th>
            Total
        </th>
    </thead>
    <tbody>
        <tr>
            <td>
                $@ViewBag.totalBanco
            </td>
            <td>
                $@ViewBag.totalCaja
            </td>
            <td>
                $@ViewBag.total
            </td>
        </tr>
    </tbody>
</table>