SistemaConsorcio/Models/Movimientos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaConsorcio.Models
{
    public class Movimientos
    {
        public int MovimientosId { get; set; }
        [Display(Name = "Descripcion")]
        public string MovimientosDescripcion { get; set; }
        [Display(Name = "Pagado?")]
        public bool MovimientosPagado { get; set; }
        [Display(Name = "Importe")]
        [Required(ErrorMessage = "Debe ingresar un importe")]
        public decimal MovimientosImporte { get; set; }
        [Display(Name = "Rubro")]
        public int RubroExpensaId { get; set; }
        [Display(Name = "Rubro")]
        public RubroExpensa MovimientosRubro { get; set; }
        public int ExpensaId { get; set; }
        public Expensa MovimientosExpensa { get; set; }
        [Display(Name = "Es informacion economica?")]
        public bool MovimientosInformacion { get; set; }//indica si es info economica para saber donde va, y si tiene vencimiento

    }
}

SistemaConsorcio/Controllers/ExpensasController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class ExpensasController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ExpensasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> getExpensas()
        {
            return PartialView("_Index",await _context.Expensa.OrderByDescending(e => e.ExpensaPeriodo).ToListAsync());
        }

        public async Task<IActionResult> getExpensaActual()
        {
            var configuracion = await _context.General.FirstOrDefaultAsync();
            var id = configuracion.GeneralExpensaActiva;
            var expensa = await _context.Expensa.FindAsync(id);
            return PartialView("_Carga",expensa);
        }

        // GET: Expensas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var expensa = await _context.Expensa
                .FirstOrDefaultAsync(m => m.ExpensaId == id);
            if (expensa == null)
            {
                return NotFound();
            }
            ViewBag.subTotal = await calcularTotalExpensa(expensa) - expensa.ExpensaReserva;
            return PartialView(expensa);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ExpensaId,ExpensaPeriodo,ExpensaConfirmada")] Expensa expensa)
        {
            DateTime date = DateTime.Now;
            DateTime oPrimerDiaDelMes = new DateTime(date.Year, date.Month, 1);
            DateTime oUltimoDiaDelMes = oPrimerDiaDelMes.AddMonths(1).AddDays(-1);
            expensa.ExpensaPeriodo = oUltimoDiaDelMes;
            var expensas = from e in _context.Expensa
                                where (e.ExpensaPeriodo.Month == expensa.ExpensaPeriodo.Month) && ( e.ExpensaPeriodo.Year == expensa.ExpensaPeriodo.Year)
                                select e;
            if (expensas.Count() > 0)
            {
                return Json(new { exitoso = false, alerta = "Ya hay una expensa cargada para el mes" });
            }
            expensa.ExpensaReserva = 0;
            _context.Add(expensa);
            await _context.SaveChangesAsync();
            var configuracion = await _context.General.FirstOrDefaultAsync();
            configuracion.GeneralExpensaActiva = expensa.ExpensaId;
            await _context.SaveChangesAsync();
            return Json(new { exitoso = true, alerta = "Agregado correctamente",id = expensa.ExpensaId });
        }

        public async Task<IActionResult> ConfirmarExpensa(int id)
        {
            var expensa = await _context.Expensa.FindAsync(id);
            var general = await _context.General.FirstOrDefaultAsync();
            await generarPagos(expensa);
            expensa.ExpensaConfirmada = true;
            general.GeneralExpensaActiva = 0;
            _context.Update(expensa);
            _context.Update(general);
            if (general.GeneralEnvioMails)
            {
                await SendAllMailsExpensa(expensa);
            }
            await _context.SaveChangesAsync();
            return Json(true);
        }

        private async Task<IActionResult> generarPagos(Expensa expensa)
        {
            var departamentos = await _context.Departamento.ToListAsync();
            var crearPagoPendiente = new PagoPendientesController(_context);
            var totalExpensa = await calcularTotalExpensa(expensa);
            var totalCochera = await calcularTotalCochera(totalExpensa);
            var cantidadCocheras = departamentos.Sum(d => d.DepartamentoCantidadCochera);
            var totalDepartamento = totalExpensa - (totalCochera*cantidadCocheras);
            PagoPendiente fechas = await calcularFechaVencimientos(expensa.ExpensaPeriodo);
            foreach (Departamento departamento in departamentos)
            {
                await crearPagoPendiente.Create(await generarPagoPendiente(expensa, departamento, totalDepartamento, fechas, totalCochera));
            }
            return Json(true);
        }

        private async Task<PagoPendiente> calcularFechaVencimientos(DateTime periodoExpensa)
        {
            var configuracion = await _context.General.FirstAsync();
            periodoExpensa = periodoExpensa.AddDays(1);
            var conteo = 1;
            PagoPendiente aux = new PagoPendiente();
            while (conteo <= configuracion.GeneralDiaTercerVencimiento)
            {
                if (periodoExpensa.DayOfWeek == DayOfWeek.Saturday && configuracion.GeneralVencimientoHabiles)
                {
                    periodoExpensa = periodoExpensa.AddDays(2);
                }
                if (periodoExpensa.DayOfWeek == DayOfWeek.Sunday && configuracion.GeneralVencimientoHabiles)
                {
                    periodoExpensa = periodoExpensa.AddDays(1);
                }
                if (configuracion.GeneralDiaPrimerVencimiento == conteo)
                {
                    aux.PagoPendienteFechaPrimerVencimiento = periodoExpensa;
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
                else if (configuracion.GeneralDiaSegundoVencimiento == conteo)
                {
                    aux.PagoPendienteFechaSegundoVencimiento = periodoExpensa;
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
                else if (configuracion.GeneralDiaTercerVencimiento == conteo)
                {
                    aux.PagoPendienteFechaTercerVencimiento = periodoExpensa;
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
                else
                {
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
            }
            return aux;
        }
        private async Task<PagoPendiente> generarPagoPendiente(Expensa expensa, Departamento departamento, decimal totalExpensa, PagoPendiente fechas, decimal totalCochera)
        {
            var tipo = new TipoDepartamento();
            decimal importe = 0;
            var descripcion = "Departamento";
            if (departamento.DepartamentoCochera)
            {
                tipo = await _context.TipoDepartamento
                        .FirstOrDefaultAsync(t => t.TipoDepartamentoLetra == "Z");
                importe += totalCochera*departamento.DepartamentoCantidadCochera;
                descripcion += "/Cochera";
            }
            tipo = await _context.TipoDepartamento
                      .FirstOrDefaultAsync(t => t.TipoDepartamentoId == departamento.TipoDepartamentoId);
            importe += (((totalExpensa) * tipo.TipoDepartamentoCoeficiente) / 100);
            importe = roundImport(importe,departamento);
            var nuevoPagoPendiente = new PagoPendiente
            {
                ExpensaId = expensa.ExpensaId,
                DepartamentoId = departamento.DepartamentoId,
                PagoPendienteImporte = importe,
                PagoPendienteFechaPrimerVencimiento = fechas.PagoPendienteFechaPrimerVencimiento,
                PagoPendienteFechaSegundoVencimiento = fechas.PagoPendienteFechaSegundoVencimiento,
                PagoPendienteFechaTercerVencimiento = fechas.PagoPendienteFechaTercerVencimiento,
                PagoPendienteDescripcion = descripcion
            };
            var general = await _context.General.FirstOrDefaultAsync();
            nuevoPagoPendiente.PagoPendientePrimerVencimiento = roundImport(Math.Floor(nuevoPagoPendiente.PagoPendienteImporte + ((nuevoPagoPendiente.PagoPendienteImporte * general.GeneralPrimerVencimiento) / 100)),departamento);
            nuevoPagoPendiente.PagoPendienteSegundoVencimiento = roundImport(Math.Floor(nuevoPagoPendiente.PagoPendienteImporte + ((nuevoPagoPendiente.PagoPendienteImporte * general.GeneralSegundoVencimiento) / 100)),departamento);
            nuevoPagoPendiente.PagoPendienteTercerVencimiento = roundImport(Math.Floor(nuevoPagoPendiente.PagoPendienteImporte + ((nuevoPagoPendiente.PagoPendienteImporte * general.GeneralTercerVencimiento) / 100)),departamento);
            nuevoPagoPendiente.PagoPendienteBono = await crearBonoPago(nuevoPagoPendiente);
            return nuevoPagoPendiente;
        }

        private decimal roundImport(decimal importe, Departamento departamento)
        {
            string sufixChar = null;
            if (departamento.DepartamentoSufix.ToString().Length == 1)
            {
                sufixChar = "0.0" + departamento.DepartamentoSufix;
            }
            else
            {
                sufixChar = "0." + departamento.DepartamentoSufix;
            }
            decimal sufix = Convert.ToDecimal(sufixChar);
            importe = Math.Floor(importe);
            return importe+sufix;
        }
        public async Task<byte[]> crearBonoPago(PagoPendiente pago)
        {
            ReportePago datos = new ReportePago();
            datos.general = await _context.General.FirstOrDefaultAsync();
            datos.expensa = await _context.Expensa.Where(e => e.ExpensaId == pago.ExpensaId).FirstAsync();
            datos.departamento = await _context.Departamento.Include(d => d.DepartamentoPropietario).Include(d => d.DepartamentoTipo).Where(d => d.DepartamentoId == pago.DepartamentoId).FirstAsync();
            datos.pagoPendiente = pago;
            datos.totalExpensa = await calcularTotalExpensa(datos.expensa);

SistemaConsorcio/Controllers/MovimientosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class MovimientosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MovimientosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movimientos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Movimientos.Include(m => m.MovimientosExpensa).Include(m => m.MovimientosRubro);
            return View(await applicationDbContext.ToListAsync());
        }
        public async  Task<IActionResult> getMovimientosExpensa(int? id)
        {
            var applicationDbContext = _context.Movimientos
                .Include(m => m.MovimientosExpensa)
                .Include(m => m.MovimientosRubro)
                .Where(m => m.ExpensaId == id)
                .OrderBy(m => m.MovimientosRubro.RubroExpensaDescripcion);
            ViewBag.expensa = id;
            return PartialView("_index", await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> getInfoMovimientosExpensa(int? id)
        {
            var applicationDbContext = _context.Movimientos
                .Include(m => m.MovimientosExpensa)
                .Include(m => m.MovimientosRubro)
                .Where(m => m.ExpensaId == id)
                .OrderBy(m => m.MovimientosRubro.RubroExpensaDescripcion); 
            return PartialView("_InfoMovimientos", await applicationDbContext.ToListAsync());
        }

        // GET: Movimientos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientos = await _context.Movimientos
                .Include(m => m.MovimientosExpensa)
                .Include(m => m.MovimientosRubro)
                .FirstOrDefaultAsync(m => m.MovimientosId == id);
            if (movimientos == null)
            {
                return NotFound();
            }

            return View(movimientos);
        }

        // GET: Movimientos/Create
        public IActionResult Create(int? id)
        {
            ViewData["RubroExpensaId"] = new SelectList(_context.RubroExpensa.OrderBy(m => m.RubroExpensaDescripcion), "RubroExpensaId", "RubroExpensaDescripcion");
            ViewBag.idExpensa = id;
            return PartialView();
        }

        // POST: Movimientos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovimientosId,MovimientosDescripcion,MovimientosPagado,MovimientosImporte,RubroExpensaId,ExpensaId,MovimientosInformacion")] Movimientos movimientos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movimientos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExpensaId"] = new SelectList(_context.Expensa, "ExpensaId", "ExpensaId", movimientos.ExpensaId);
            ViewData["RubroExpensaId"] = new SelectList(_context.RubroExpensa, "RubroExpensaId", "RubroExpensaId", movimientos.RubroExpensaId);
            return View(movimientos);
        }

        [HttpPost]
        public async Task<IActionResult> Agregar([Bind("MovimientosId,MovimientosDescripcion,MovimientosPagado,MovimientosImporte,RubroExpensaId,ExpensaId,MovimientosInformacion")] Movimientos movimientos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movimientos);
                await _context.SaveChangesAsync();
                return Json(new { exitoso = true, alerta = "Movimiento agregado" });
            }
            return Json(new { exitoso = false, alerta = "Error al agregar" });
        }

        // GET: Movimientos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientos = await _context.Movimientos.FindAsync(id);
            if (movimientos == null)
            {
                return NotFound();
            }
            ViewBag.idExpensa = id;
            ViewData["RubroExpensaId"] = new SelectList(_context.RubroExpensa, "RubroExpensaId", "RubroExpensaDescripcion");
            return PartialView(movimientos);
        }

        [HttpPost]
        public async Task<IActionResult> ActualizarMovimiento([Bind("MovimientosId,MovimientosDescripcion,MovimientosPagado,MovimientosImporte,RubroExpensaId,ExpensaId,MovimientosInformacion")] Movimientos movimientos)
        {
            if (ModelState.IsValid)
            {
                _context.Update(movimientos);
                await _context.SaveChangesAsync();
                return Json(new { exitoso = true, alerta = "Movimiento actualizado" });
            }
            return Json(new { exitoso = false, alerta = "Error al agregar"});
        }

        // GET: Movimientos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var movimientos = await _context.Movimientos.FindAsync(id);
            _context.Movimientos.Remove(movimientos);
            await _context.SaveChangesAsync();
            return Json(new { eliminado = true, msg = "Movimiento eliminado" });
        }

        // POST: Movimientos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movimientos = await _context.Movimientos.FindAsync(id);
            _context.Movimientos.Remove(movimientos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovimientosExists(int id)
        {
            return _context.Movimientos.Any(e => e.MovimientosId == id);
        }
    }
}

SistemaConsorcio/Views/Movimientos/Create.cshtml
@model SistemaConsorcio.Models.Movimientos


    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Nuevo movimiento</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form asp-action="Create" class="submit-create" data-id-expensa="@ViewBag.idExpensa">
            <div class="modal-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-8">
                            <label asp-for="RubroExpensaId" class="control-label"></label>
                            <select asp-for="RubroExpensaId" class="form-control RubroExpensaId" asp-items="ViewBag.RubroExpensaId"></select>
                        </div>
                        <div class="col">
                            <div class="switch_box box_1">
                                <label class="form-check-label">
                                    <p class="control-label">Es informacion?</p><input type="checkbox" class="switch_1 InformacionEconomica" style="margin-left:30px;">
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="MovimientosDescripcion" class="control-label"></label>
                    <input asp-for="MovimientosDescripcion" class="form-control MovimientosDescripcion" />
                    <span asp-validation-for="MovimientosDescripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label asp-for="MovimientosImporte" class="control-label"></label>
                            <input class="form-control MovimientosImporte" />
                            <span asp-validation-for="MovimientosImporte" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <div class="switch_box box_1">
                                <label class="form-check-label">
                                    <p class="control-label">Pagado?</p><input type="checkbox" class="switch_1 MovimientosPagado" style="margin-left:30px;">
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark btn-quitarmodal" data-dismiss="modal">Cancelar</button>
                <input type="submit" value="Agregar" class="btn btn-primary btn-agregar" />
            </div>
        </form>
    </div>


@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    $('.InformacionEconomica').on("change", function () {
        if ($(this).prop('checked')) {
            $('.RubroExpensaId').prop("disabled", true);
            $('.RubroExpensaId').val(1);
        } else {
            $('.RubroExpensaId').prop("disabled", false);
            $('.RubroExpensaId').val(null);
        }
    }
    );
    $('.RubroExpensaId').on("change", function () {
        if ($(this).val() == 1) {
            $(this).prop("disabled", true);
            $('.InformacionEconomica').prop('checked',true);
        } 
    }
    );

    $('.submit-create').on('submit', function (e) {
        e.preventDefault();
        $('.btn-agregar').attr("disabled",true);
        let informacioneconomica = false;
        let MovimientosPagado = false;
        if ($('.InformacionEconomica').prop('checked')) {
            informacioneconomica = true;
        }
        if ($('.MovimientosPagado').prop('checked')) {
            MovimientosPagado = true;
        }
        var mov = {
            "RubroExpensaId": $('.RubroExpensaId').val(),
            "MovimientosDescripcion": $('.MovimientosDescripcion').val(),
            "MovimientosPagado": MovimientosPagado,
            "MovimientosImporte": $('.MovimientosImporte').val(),
            "ExpensaId": idexpensa,
            "MovimientosInformacion": informacioneconomica
        }
            $.ajax({
                url: "@Url.Action("Agregar","Movimientos")",
                method: 'Post',
                data: {
                    movimientos: mov
                }
            }).done((msg) => {
                if (msg.exitoso == true) {
                    alertify.success(msg.alerta);
                    $('.movimientos').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
                    $('.movimientos').load("@Url.Action("getMovimientosExpensa","Movimientos")"+'/'+idexpensa);
                    $('#ModalCU').modal('hide');
                    $('.btn-agregar').attr("disabled",false);
                } else {
                    alertify.warning(msg.alerta);
                    $('.btn-agregar').attr("disabled",false);
                }
            }).fail((err) => {
                alertify.error("Algo fallo al actualizar");
                $('.btn-agregar').attr("disabled",false);
            });
    });
    var idexpensa = $('.submit-create').data('id-expensa');
</script>

SistemaConsorcio/Views/Movimientos/_Index.cshtml
@model IEnumerable<SistemaConsorcio.Models.Movimientos>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">
                        Movimientos de la expensa 
                        <span style="display: block;float: right;">
                            <a href="" id="create-mov" data-toggle="modal" data-target="#ModalCU" data-id-expensa="@ViewBag.expensa"><i class="fas fa-plus-circle fa-2x"></i></a>
                            <a asp-action="Details" data-action="@Url.Action("Details","Expensas")/@ViewBag.expensa" class=" btn-index-ajax-nomenu"><i class="fas fa-info-circle fa-2x"></i></a>
                        </span>
                    </h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class=" text-primary">
                            <th>
                                @Html.DisplayNameFor(model => model.MovimientosRubro)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MovimientosDescripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MovimientosPagado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MovimientosImporte)
                            </th>
                            <th></th>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MovimientosRubro.RubroExpensaDescripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MovimientosDescripcion)
                                    </td>
                                    <td>
                                        @if (item.MovimientosPagado)
                                        {
                                            <i class="fas fa-check"></i>
                                        }
                                    </td>
                                    <td>
                                        $@Html.DisplayFor(modelItem => item.MovimientosImporte)
                                    </td>
                                    <td>
                                        <a href="" id="edit-mov" data-action="@Url.Action("edit","Movimientos")/@item.MovimientosId" data-toggle="modal" data-target="#ModalCU" class="btn-modal btn btn-success"><i class="fas fa-pencil-alt"></i></a>
                                    </td>
                                    <td>
                                        <a asp-action="Delete" data-action="@Url.Action("Delete")" data-id="@item.MovimientosId" class="btn btn-danger btn-delete-ajax"><i class="far fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('#create-mov').on('click', function () {
        $('.contain-CU').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
        $('.contain-CU').load("@Url.Action("Create","Movimientos")"+'/'+$(this).data('id-expensa'));
    });
    $('#edit-mov').on('click', function () {
        $('.contain-CU').html('<i class="fas fa-circle-notch fa-spin carga"></i>');
        $('.contain-CU').load($(this).data('action'));
    });
</script>

SistemaConsorcio/Views/Movimientos/_InfoMovimientos.cshtml
@model IEnumerable<SistemaConsorcio.Models.Movimientos>

@foreach (var item in Model)
{
    <div class="col-4">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">
                        <span>
                            @Html.DisplayFor(modelItem => item.MovimientosRubro.RubroExpensaDescripcion)
                        </span>
                </h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <td>Descripcion: @Html.DisplayFor(modelItem => item.MovimientosDescripcion)</td>
                            </tr>
                            <tr>
                                <td>Importe: $@Html.DisplayFor(modelItem => item.MovimientosImporte)</td>
                            </tr>
                            <tr>
                                <td>
                                    Estado:
                                    @if (item.MovimientosPagado)
                                    {
                                        <span>Pagado</span>
                                    }
                                    else
                                    {
                                        <span>No Pagado</span>
                                    }
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}