SistemaConsorcio/Controllers/ExpensasController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class ExpensasController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ExpensasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> getExpensas()
        {
            return PartialView("_Index",await _context.Expensa.OrderByDescending(e => e.ExpensaPeriodo).ToListAsync());
        }

        public async Task<IActionResult> getExpensaActual()
        {
            var configuracion = await _context.General.FirstOrDefaultAsync();
            var id = configuracion.GeneralExpensaActiva;
            var expensa = await _context.Expensa.FindAsync(id);
            return PartialView("_Carga",expensa);
        }

        // GET: Expensas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var expensa = await _context.Expensa
                .FirstOrDefaultAsync(m => m.ExpensaId == id);
            if (expensa == null)
            {
                return NotFound();
            }
            ViewBag.subTotal = await calcularTotalExpensa(expensa) - expensa.ExpensaReserva;
            return PartialView(expensa);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ExpensaId,ExpensaPeriodo,ExpensaConfirmada")] Expensa expensa)
        {
            DateTime date = DateTime.Now;
            DateTime oPrimerDiaDelMes = new DateTime(date.Year, date.Month, 1);
            DateTime oUltimoDiaDelMes = oPrimerDiaDelMes.AddMonths(1).AddDays(-1);
            expensa.ExpensaPeriodo = oUltimoDiaDelMes;
            var expensas = from e in _context.Expensa
                                where (e.ExpensaPeriodo.Month == expensa.ExpensaPeriodo.Month) && ( e.ExpensaPeriodo.Year == expensa.ExpensaPeriodo.Year)
                                select e;
            if (expensas.Count() > 0)
            {
                return Json(new { exitoso = false, alerta = "Ya hay una expensa cargada para el mes" });
            }
            expensa.ExpensaReserva = 0;
            _context.Add(expensa);
            await _context.SaveChangesAsync();
            var configuracion = await _context.General.FirstOrDefaultAsync();
            configuracion.GeneralExpensaActiva = expensa.ExpensaId;
            await _context.SaveChangesAsync();
            return Json(new { exitoso = true, alerta = "Agregado correctamente",id = expensa.ExpensaId });
        }

        public async Task<IActionResult> ConfirmarExpensa(int id)
        {
            var expensa = await _context.Expensa.FindAsync(id);
            var general = await _context.General.FirstOrDefaultAsync();
            await generarPagos(expensa);
            expensa.ExpensaConfirmada = true;
            general.GeneralExpensaActiva = 0;
            _context.Update(expensa);
            _context.Update(general);
            if (general.GeneralEnvioMails)
            {
                await SendAllMailsExpensa(expensa);
            }
            await _context.SaveChangesAsync();
            return Json(true);
        }

        private async Task<IActionResult> generarPagos(Expensa expensa)
        {
            var departamentos = await _context.Departamento.ToListAsync();
            var crearPagoPendiente = new PagoPendientesController(_context);
            var totalExpensa = await calcularTotalExpensa(expensa);
            var totalCochera = await calcularTotalCochera(totalExpensa);
            var cantidadCocheras = departamentos.Sum(d => d.DepartamentoCantidadCochera);
            var totalDepartamento = totalExpensa - (totalCochera*cantidadCocheras);
            PagoPendiente fechas = await calcularFechaVencimientos(expensa.ExpensaPeriodo);
            foreach (Departamento departamento in departamentos)
            {
                await crearPagoPendiente.Create(await generarPagoPendiente(expensa, departamento, totalDepartamento, fechas, totalCochera));
            }
            return Json(true);
        }

        private async Task<PagoPendiente> calcularFechaVencimientos(DateTime periodoExpensa)
        {
            var configuracion = await _context.General.FirstAsync();
            periodoExpensa = periodoExpensa.AddDays(1);
            var conteo = 1;
            PagoPendiente aux = new PagoPendiente();
            while (conteo <= configuracion.GeneralDiaTercerVencimiento)
            {
                if (periodoExpensa.DayOfWeek == DayOfWeek.Saturday && configuracion.GeneralVencimientoHabiles)
                {
                    periodoExpensa = periodoExpensa.AddDays(2);
                }
                if (periodoExpensa.DayOfWeek == DayOfWeek.Sunday && configuracion.GeneralVencimientoHabiles)
                {
                    periodoExpensa = periodoExpensa.AddDays(1);
                }
                if (configuracion.GeneralDiaPrimerVencimiento == conteo)
                {
                    aux.PagoPendienteFechaPrimerVencimiento = periodoExpensa;
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
                else if (configuracion.GeneralDiaSegundoVencimiento == conteo)
                {
                    aux.PagoPendienteFechaSegundoVencimiento = periodoExpensa;
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
                else if (configuracion.GeneralDiaTercerVencimiento == conteo)
                {
                    aux.PagoPendienteFechaTercerVencimiento = periodoExpensa;
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
                else
                {
                    periodoExpensa = periodoExpensa.AddDays(1);
                    conteo++;
                }
            }
            return aux;
        }
        private async Task<PagoPendiente> generarPagoPendiente(Expensa expensa, Departamento departamento, decimal totalExpensa, PagoPendiente fechas, decimal totalCochera)
        {
            var tipo = new TipoDepartamento();
            decimal importe = 0;
            var descripcion = "Departamento";
            if (departamento.DepartamentoCochera)
            {
                tipo = await _context.TipoDepartamento
                        .FirstOrDefaultAsync(t => t.TipoDepartamentoLetra == "Z");
                importe += totalCochera*departamento.DepartamentoCantidadCochera;
                descripcion += "/Cochera";
            }
            tipo = await _context.TipoDepartamento
                      .FirstOrDefaultAsync(t => t.TipoDepartamentoId == departamento.TipoDepartamentoId);
            importe += (((totalExpensa) * tipo.TipoDepartamentoCoeficiente) / 100);
            importe = roundImport(importe,departamento);
            var nuevoPagoPendiente = new PagoPendiente
            {
                ExpensaId = expensa.ExpensaId,
                DepartamentoId = departamento.DepartamentoId,
                PagoPendienteImporte = importe,
                PagoPendienteFechaPrimerVencimiento = fechas.PagoPendienteFechaPrimerVencimiento,
                PagoPendienteFechaSegundoVencimiento = fechas.PagoPendienteFechaSegundoVencimiento,
                PagoPendienteFechaTercerVencimiento = fechas.PagoPendienteFechaTercerVencimiento,
                PagoPendienteDescripcion = descripcion
            };
            var general = await _context.General.FirstOrDefaultAsync();
            nuevoPagoPendiente.PagoPendientePrimerVencimiento = roundImport(Math.Floor(nuevoPagoPendiente.PagoPendienteImporte + ((nuevoPagoPendiente.PagoPendienteImporte * general.GeneralPrimerVencimiento) / 100)),departamento);
            nuevoPagoPendiente.PagoPendienteSegundoVencimiento = roundImport(Math.Floor(nuevoPagoPendiente.PagoPendienteImporte + ((nuevoPagoPendiente.PagoPendienteImporte * general.GeneralSegundoVencimiento) / 100)),departamento);
            nuevoPagoPendiente.PagoPendienteTercerVencimiento = roundImport(Math.Floor(nuevoPagoPendiente.PagoPendienteImporte + ((nuevoPagoPendiente.PagoPendienteImporte * general.GeneralTercerVencimiento) / 100)),departamento);
            nuevoPagoPendiente.PagoPendienteBono = await crearBonoPago(nuevoPagoPendiente);
            return nuevoPagoPendiente;
        }

        private decimal roundImport(decimal importe, Departamento departamento)
        {
            string sufixChar = null;
            if (departamento.DepartamentoSufix.ToString().Length == 1)
            {
                sufixChar = "0.0" + departamento.DepartamentoSufix;
            }
            else
            {
                sufixChar = "0." + departamento.DepartamentoSufix;
            }
            decimal sufix = Convert.ToDecimal(sufixChar);
            importe = Math.Floor(importe);
            return importe+sufix;
        }
        public async Task<byte[]> crearBonoPago(PagoPendiente pago)
        {
            ReportePago datos = new ReportePago();
            datos.general = await _context.General.FirstOrDefaultAsync();
            datos.expensa = await _context.Expensa.Where(e => e.ExpensaId == pago.ExpensaId).FirstAsync();
            datos.departamento = await _context.Departamento.Include(d => d.DepartamentoPropietario).Include(d => d.DepartamentoTipo).Where(d => d.DepartamentoId == pago.DepartamentoId).FirstAsync();
            datos.pagoPendiente = pago;
            datos.totalExpensa = await calcularTotalExpensa(datos.expensa);

SistemaConsorcio/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaConsorcio.Data;
using SistemaConsorcio.Models;

namespace SistemaConsorcio.Controllers
{
    [Authorize]
    public class PagosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PagosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pagos
        public IActionResult Index()
        {
            return PartialView();
        }

        public async Task<IActionResult> getPagos(DateTime? fechaDesde,DateTime? fechaHasta)
        {
            var pagos = from p in _context.Pago
                           select p;
            pagos = _context.Pago.Include(p => p.PagoDepartamento).Include(p => p.PagoDepartamento.DepartamentoTipo).OrderByDescending(p => p.PagoFecha);
            DateTime date = DateTime.Now;
            DateTime oPrimerDiaDelMes = new DateTime(date.Year, date.Month, 1);
            if (!String.IsNullOrEmpty(fechaDesde.ToString()))
            {
                pagos = pagos.Where(p => p.PagoFecha >= fechaDesde);
            }
            else
            {
                pagos = pagos.Where(p => p.PagoFecha >= oPrimerDiaDelMes);
            }
            if (!String.IsNullOrEmpty(fechaHasta.ToString()))
            {
                pagos = pagos.Where(p => p.PagoFecha <= fechaHasta);
            }
            else
            {
                DateTime oUltimoDiaDelMes = oPrimerDiaDelMes.AddMonths(1).AddDays(-1);
                pagos = pagos.Where(p => p.PagoFecha <= oUltimoDiaDelMes);
            }
            ViewBag.totalBanco = pagos.Where(p => p.PagoForma == "Cuenta bancaria").Sum(p => p.PagoImporte);
            ViewBag.totalCaja = pagos.Where(p => p.PagoForma == "Contado").Sum(p => p.PagoImporte);
            ViewBag.total = ViewBag.totalBanco + ViewBag.totalCaja;
            return PartialView("_Listado",await pagos.ToListAsync());
        }
        // GET: Pagos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago
                .Include(p => p.PagoDepartamento)
                .FirstOrDefaultAsync(m => m.PagoId == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // GET: Pagos/Create
        public IActionResult Create()
        {
            var departamentos =
                      _context.Departamento.Include(d => d.DepartamentoTipo)
                        .Select(d => new
                        {
                            d.DepartamentoId,
                            NombreDeparamento = string.Format("{0}°{1}", d.DepartamentoPiso, d.DepartamentoTipo.TipoDepartamentoLetra)
                        })
                        .ToList();
            ViewData["DepartamentoId"] = new SelectList(departamentos, "DepartamentoId", "NombreDeparamento");
            ViewData["ExpensaId"] = new SelectList(_context.Expensa, "ExpensaId", "ExpensaId");
            return PartialView();
        }

        // POST: Pagos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("PagoId,PagoFecha,DepartamentoId,PagoImporte,PagoForma")] Pago pago, int TipoPago)
        {
            if (ModelState.IsValid)
            {
                if (TipoPago == 0)
                {
                    await eliminarPagosPendientesDepartamento(pago.DepartamentoId);
                }
                _context.Add(pago);
                await _context.SaveChangesAsync();
                return Json(new { exitoso = true, alerta = "Pago cargado" });
            }
            return Json(new { exitoso = false, alerta = "Error al cargar pago" });
        }

        public async Task<IActionResult> eliminarPagosPendientesDepartamento(int idDepartamento)
        {
            var pendientes = await _context.PagoPendiente.Where(pp => pp.DepartamentoId == idDepartamento).ToListAsync();
            var controladorPendientes = new PagoPendientesController(_context);
            foreach (PagoPendiente pendiente in pendientes)
            {
                await controladorPendientes.Delete(pendiente.PagoPendienteId);   
            }
            return Json(true);
        }
        // GET: Pagos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago.FindAsync(id);
            if (pago == null)
            {
                return NotFound();
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamento, "DepartamentoId", "DepartamentoId", pago.DepartamentoId);
            return View(pago);
        }

        // POST: Pagos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PagoId,PagoFecha,DepartamentoId,PagoImporte,PagoForma")] Pago pago)
        {
            if (id != pago.PagoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagoExists(pago.PagoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoId"] = new SelectList(_context.Departamento, "DepartamentoId", "DepartamentoId", pago.DepartamentoId);
            return View(pago);
        }

        // GET: Pagos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago
                .Include(p => p.PagoDepartamento)
                .FirstOrDefaultAsync(m => m.PagoId == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // POST: Pagos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pago = await _context.Pago.FindAsync(id);
            _context.Pago.Remove(pago);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagoExists(int id)
        {
            return _context.Pago.Any(e => e.PagoId == id);
        }
    }
}

SistemaConsorcio/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SistemaConsorcio</title>
    <environment include="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
              asp-fallback-href="~/fontawesome/css/all.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
              asp-fallback-href="~/fontawesome/css/all.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- CSS -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css" />
    <!-- Default theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/themes/default.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
</head>
<body>
    <span class="todo-contenido">
    @if (SignInManager.IsSignedIn(User))
    {
        <div class="d-flex" id="wrapper" style="min-height:100%;">
            <!-- Sidebar -->
            <div class="bg-white border-right" id="sidebar-wrapper">
                <div class="sidebar-heading">@ViewData["nombre_consorcio"]</div>
                <div class="list-group list-group-flush">
                    <a href="" data-action="@Url.Action("getInicio")" class="list-group-item list-group-item-action btn-index-ajax active home-btn"><i class="fas fa-home"></i> Inicio</a>
                    <a href="" data-action="@Url.Action("getPropietarios","Propietarios")" class="list-group-item list-group-item-action btn-index-ajax"><i class="fas fa-users"></i> Propietarios</a>
                    <a href="#deptosSubmenu" data-toggle="collapse" aria-expanded="false" class="list-group-item list-group-item-action"><i class="fas fa-building"></i> Departamentos <i class="fas fa-sort-down"></i></a>
                    <div class="collapse list-unstyled list-group-item-action" id="deptosSubmenu">
                        <a href="#" data-action="@Url.Action("getDepartamentos","Departamentos")" class="list-group-item list-group-item-action btn-index-ajax">&nbsp;&nbsp;<i class="fas fa-book"></i> Listado</a>
                        <a href="#" data-action="@Url.Action("getTipos","TiposDepartamentos")" class="list-group-item list-group-item-action btn-index-ajax">&nbsp;&nbsp;<i class="fas fa-home"></i> Tipos</a>
                    </div>
                    <a href="#expSubmenu" data-toggle="collapse" aria-expanded="false" class="list-group-item list-group-item-action"><i class="fas fa-user-tag"></i> Expensas <i class="fas fa-sort-down"></i></a>
                    <div class="collapse list-unstyled list-group-item-action" id="expSubmenu">
                        <a href="" data-action="@Url.Action("getExpensaActual","Expensas")" class="list-group-item list-group-item-action btn-index-ajax btn-gestion">&nbsp;&nbsp;<i class="fas fa-cash-register"></i> Gestionar</a>
                        <a href="" data-action="@Url.Action("getExpensas","Expensas")" class="list-group-item list-group-item-action btn-index-ajax btn-historial">&nbsp;&nbsp;<i class="fas fa-clipboard-list"></i> Historial</a>
                        <a href="" data-action="@Url.Action("getRubroExpensas","RubroExpensas")" class="list-group-item list-group-item-action btn-index-ajax">&nbsp;&nbsp;<i class="fas fa-tag"></i> Rubros</a>
                    </div>
                    <a href="" data-action="@Url.Action("Index","Pagos")" class="list-group-item list-group-item-action btn-index-ajax"><i class="fas fa-money-bill-alt"></i> Pagos</a>
                    <a href="" data-action="@Url.Action("getConfiguracion","Generales")" class="list-group-item list-group-item-action btn-index-ajax"><i class="fas fa-cogs"></i> Configuración</a>
                </div>
            </div>
            <!-- /#sidebar-wrapper -->
            <!-- Page Content -->
            <div id="page-content-wrapper">

                <nav class="navbar navbar-expand-lg navbar-light bg-light ">
                    <button class="btn btn-primary" id="menu-toggle"><i class="fas fa-bars"></i></button>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <partial name="_LoginPartial" />
                        </ul>
                    </div>
                </nav>
                <div class="container">
                    @RenderBody()
                </div>
                <!-- Modal CREATE UPDATE-->
                <div class="modal fade" id="ModalCU" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-xl contain-CU" role="document">

                    </div>
                </div>
            </div>
            <!-- /#page-content-wrapper -->

        </div>

    }
    else
    {
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    }
        </span>
    <div class="charge d-none" style="text-align:center;width:100%;margin-top:150px;">
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/alertify.min.js"></script>
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>